---
- hosts: server
  user: ranjan
  become: yes
  connection: ssh
  tasks:
    - name: install httpd on linux
      action: yum name=httpd state=present
    - name: restart
      action: service name=httpd state=restart
