---
- hosts: server
  user: ranjan1
  become: yes
  connection: ssh
  tasks:
    - name: install httpd on linux
      action: yum name=httpd state=present
    - name: restart
      action: service name=httpd state=restarted
    - name: copy
      copy:
        src: webapp/target/webapp.war
        dest: /usr/local/tomcat10/webapps/
    
